In [1]:
emp = {'name':'Kiran','gender':'male','email':'abc@gmail.com'}

In [2]:
emp

{'name': 'Kiran', 'gender': 'male', 'email': 'abc@gmail.com'}

In [15]:
type(emp)

dict

In [7]:
for key, value in emp.items():
    print(key)
    print(value)
    print(key,'->',value)

name
Kiran
name -> Kiran
gender
male
gender -> male
email
abc@gmail.com
email -> abc@gmail.com

In [8]:
import pandas as pd

In [16]:
df_emp = pd.DataFrame(emp,index=[0])

In [17]:
df_emp

    name gender          email
0  Kiran   male  abc@gmail.com

In [18]:
emp = {'name':['Kiran','Krish','John'],'gender':['male','male','male'],'email':['abc@gmail.com','def@gmail.com','ghi@gmail.com']}

In [19]:
emp

{'name': ['Kiran', 'Krish', 'John'],
 'gender': ['male', 'male', 'male'],
 'email': ['abc@gmail.com', 'def@gmail.com', 'ghi@gmail.com']}

In [20]:
df_emp = pd.DataFrame(emp)

In [21]:
df_emp

    name gender          email
0  Kiran   male  abc@gmail.com
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [24]:
df_emp['name']

0    Kiran
1    Krish
2     John
Name: name, dtype: object

In [25]:
type(df_emp)

pandas.core.frame.DataFrame

In [27]:
df_emp['name']

0    Kiran
1    Krish
2     John
Name: name, dtype: object

In [28]:
df_emp.name

0    Kiran
1    Krish
2     John
Name: name, dtype: object

In [30]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   gender  3 non-null      object
 2   email   3 non-null      object
dtypes: object(3)
memory usage: 200.0+ bytes

In [32]:
df_emp.describe()

         name gender          email
count       3      3              3
unique      3      1              3
top     Kiran   male  abc@gmail.com
freq        1      3              1

In [33]:
type(df_emp['name'])

pandas.core.series.Series

In [34]:
col = ['name','gender']
df_emp[col]

    name gender
0  Kiran   male
1  Krish   male
2   John   male

In [36]:
# iloc - integer or index based
# oth row and oth colu
# [r,c]
df_emp.iloc[0,0]

'Kiran'

In [37]:
# first row
df_emp.iloc[0]

name              Kiran
gender             male
email     abc@gmail.com
Name: 0, dtype: object

In [38]:
df_emp

    name gender          email
0  Kiran   male  abc@gmail.com
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [41]:
# rows from 1 to 3 (3 will not be considered but till 2)
df_emp.iloc[1:3]

    name gender          email
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [42]:
# rows between 1 and 3 (3 will not be considered but till 2) and 0 to 2 columns (0th and 1st index as 2 will not be considered)
df_emp.iloc[1:3,0:2]

    name gender
1  Krish   male
2   John   male

In [44]:
#what if we want random rows like 0th and 2nd row along with 1st and 2nd column
df_emp.iloc[[0,2],[1,2]]

  gender          email
0   male  abc@gmail.com
2   male  ghi@gmail.com

In [45]:
# loc - label based
df_emp.loc[1]

name              Krish
gender             male
email     def@gmail.com
Name: 1, dtype: object

In [46]:
df_emp.loc[1,'name']

'Krish'

In [47]:
df_emp

    name gender          email
0  Kiran   male  abc@gmail.com
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [49]:
# here lable 2 is also included in the result. where as with iloc, last index will be ignored as iloc is more on index based
# give all rows from 0 to 2 and give me only name and email columns
df_emp.loc[0:2,['name','email']]

    name          email
0  Kiran  abc@gmail.com
1  Krish  def@gmail.com
2   John  ghi@gmail.com

In [50]:
# give all rows from 0 to 2 and give all the columns from name to email
df_emp.loc[0:2,'name':'email']

    name gender          email
0  Kiran   male  abc@gmail.com
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [51]:
# reset index. give email as index column
df_emp.set_index('email')

                name gender
email
abc@gmail.com  Kiran   male
def@gmail.com  Krish   male
ghi@gmail.com   John   male

In [54]:
df_emp

    name gender          email
0  Kiran   male  abc@gmail.com
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [55]:
emp = {'name':['Kiran','Krish','John'],'gender':['male','male','male'],'email':['abc@gmail.com','def@gmail.com','ghi@gmail.com']}

In [56]:
df=pd.DataFrame(emp)

In [57]:
fc=(df['gender']=='male')
df[fc]

    name gender          email
0  Kiran   male  abc@gmail.com
1  Krish   male  def@gmail.com
2   John   male  ghi@gmail.com

In [59]:
fc= ~(df['gender']=='male')
df[fc]

Empty DataFrame
Columns: [name, gender, email]
Index: []